import type { Metadata } from "next"
import { Raleway } from "next/font/google"

import { cn } from "@/lib/utils"
import "./globals.css"

const raleway = Raleway({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					"bg-[#010315] text-white py-12",
					raleway.className
				)}
			>
				{children}
			</body>
		</html>
	)
}
